### ISSUE TITLE
Webpack errors upon fresh repo clone / npm install

### ISSUE THREAD

**Issue by altruisticsoftware** [jquintozamora/react-typescript-webpack2-cssModules-postCSS#367]
OSX: 10.14.1
Node: 8.12.0
Npm: 6.4.1

```
ERROR in ./app/stylesheets/main.css (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./app/stylesheets/main.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/Users/chris/hmm/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/Users/chris/hmm/node_modules/css-loader/dist/index.js:44:28)
 @ ./app/stylesheets/main.css 2:14-146 21:1-42:3 22:19-151
 @ ./app/src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./app/src/index.tsx

ERROR in ./app/src/components/Header/Header.module.css (./node_modules/typings-for-css-modules-loader/lib??ref--8-1!./node_modules/postcss-loader/src??ref--8-2!./app/src/components/Header/Header.module.css)
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
Error: Cannot find module 'css-loader/locals'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chris/hmm/node_modules/typings-for-css-modules-loader/lib/index.js:9:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/chris/hmm/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/chris/hmm/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/chris/hmm/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/chris/hmm/node_modules/webpack/lib/NormalModule.js:280:3)
 @ ./app/src/components/Header/Header.module.css 2:14-188 21:1-42:3 22:19-193
 @ ./app/src/components/Header/Header.tsx
 @ ./app/src/containers/App/App.tsx
 @ ./app/src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./app/src/index.tsx

ERROR in ./app/src/components/Viewer/Viewer.module.css (./node_modules/typings-for-css-modules-loader/lib??ref--8-1!./node_modules/postcss-loader/src??ref--8-2!./app/src/components/Viewer/Viewer.module.css)
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
Error: Cannot find module 'css-loader/locals'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chris/hmm/node_modules/typings-for-css-modules-loader/lib/index.js:9:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/chris/hmm/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/chris/hmm/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/chris/hmm/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/chris/hmm/node_modules/webpack/lib/NormalModule.js:280:3)
 @ ./app/src/components/Viewer/Viewer.module.css 2:14-188 21:1-42:3 22:19-193
 @ ./app/src/components/Viewer/Viewer.tsx
 @ ./app/src/containers/App/App.tsx
 @ ./app/src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./app/src/index.tsx

ERROR in ./app/src/components/AsyncLoading/AsyncLoading.module.css (./node_modules/typings-for-css-modules-loader/lib??ref--8-1!./node_modules/postcss-loader/src??ref--8-2!./app/src/components/AsyncLoading/AsyncLoading.module.css)
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
Error: Cannot find module 'css-loader/locals'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chris/hmm/node_modules/typings-for-css-modules-loader/lib/index.js:9:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/chris/hmm/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/chris/hmm/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/chris/hmm/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/chris/hmm/node_modules/webpack/lib/NormalModule.js:280:3)
 @ ./app/src/components/AsyncLoading/AsyncLoading.module.css 2:14-194 21:1-42:3 22:19-199
 @ ./app/src/components/AsyncLoading/AsyncLoading.tsx
 @ ./app/src/containers/App/App.tsx
 @ ./app/src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./app/src/index.tsx
Child HtmlWebpackCompiler:
                          Asset     Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  558 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html] 1.91 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by jquintozamora** [comment]
Hi @altruisticsoftware , 
Thanks for letting me know, sounds like typings-for-css-modules-loader has an issue with css-loader@2.

Please grab latest and test it again.

Cheers

**Comment by altruisticsoftware** [comment]
Sweet deal! That worked. Thanks @jquintozamora
